Riizu/rush-hour

Gemfile
test/test_helper.rb

-- implemented database cleaner gem - closes #1

implemented database cleaner gem - closes #1

---

Gemfile
Gemfile.lock
Rakefile

--added rake test to rakefile
--closes #2

added rake test to rakefile closes #2

---

db/migrate/20160517195810_create_payload_requests.rb
db/schema.rb

--created payload requests db
--closes #3

created payload requests db closes #3

---

app/models/payload_request.rb
dtr.md
test/models/payload_request_test.rb

--added: PayloadRequest.rb
Tested using Tux, until we know how to test ActiveRecord.

Implemented PayloadRequest model. Closes #4

---

app/models/payload_request.rb
db/migrate/20160517204819_add_column_payload_requests.rb
db/schema.rb

-Modified: payload_request.rb (implemented validation)

Initial validation added for the PayloadRequests table. Closes #5

---

db/schema_planner.xml

Utilized the schema planner to develop a basic database layout.
-Added: schema-planner.xml

Created schema plan

---

app/models/event_name.rb
app/models/ip.rb
app/models/payload_request.rb
app/models/referrer.rb
app/models/request_type.rb
app/models/resolution.rb
app/models/url.rb
app/models/user_agent.rb
db/migrate/20160517222618_update_payload_requests_table.rb
db/migrate/20160517223318_create_urls.rb
db/migrate/20160517223559_create_request_types.rb
db/migrate/20160517223652_create_resolutions.rb
db/migrate/20160517223739_create_user_agents.rb
db/migrate/20160517223810_create_referrers.rb
db/migrate/20160517223834_create_event_names.rb
db/migrate/20160517223857_create_ips.rb
db/schema.rb

created migrations for new schema
finished establishing relationships for iteration 1

Create schema plan 8

---

app/models/payload_request.rb

Modified: PayloadRequest
Added verification checks to ensure all ID's are present.

Re-added verification to the PayloadRequest model

---

app/models/payload_request.rb
test/models/payload_request_test.rb
test/test_helper.rb

--finished request analytics - response times
--closes #16

finished request analytics - response times - closes #16

---

Gemfile
Gemfile.lock
app/models/event_name.rb
app/models/payload_request.rb
app/models/request_type.rb
app/models/resolution.rb
app/models/url.rb
app/models/user_agent.rb
test/models/event_name_test.rb
test/models/payload_request_test.rb
test/models/request_type_test.rb
test/models/resolution_test.rb
test/models/user_agent_test.rb

finished first half of analytics for iteration 2.  Closes waffle item #18.

finished first half of analytics closes #18

---

app/models/payload_request.rb
app/models/url.rb
test/models/url_test.rb

--URL analytics response times 
--closes #20

url analytics response times - closes #20

---

app/models/referrer.rb
app/models/request_type.rb
app/models/url.rb
test/models/event_name_test.rb
test/models/payload_request_test.rb
test/models/resolution_test.rb
test/models/url_test.rb
test/models/user_agent_test.rb
test/test_helper.rb

Implemented: 
Average Response time for our clients app across all requests
Max Response time across all requests
Min Response time across all requests
Most frequent request type
List of all HTTP verbs used
List of URLs listed form most requested to least requested
Web browser breakdown across all requests(userAgent)
OS breakdown across all requests(userAgent)
Screen Resolutions across all requests (resolutionWidth x resolutionHeight)
Events listed from most received to least.
Our client also finds it valuable to have stats on specific URLs. For a specific URL, let's find the following Stats:
Max Response time
Min Response time
A list of response times across all requests listed from longest response time to shortest response time.
Average Response time for this URL
HTTP Verb(s) …

Iteration 2 Complete

---

app/models/client.rb
app/models/event_name.rb
app/models/ip.rb
app/models/payload_request.rb
app/models/referrer.rb
app/models/request_type.rb
app/models/resolution.rb
app/models/url.rb
app/models/user_agent.rb
db/migrate/20160519165949_create_clients.rb
db/migrate/20160519170345_add_client_to_payload_requests.rb
db/migrate/20160519170556_update_client_inside_payload_requests.rb
db/schema.rb
test/models/client_test.rb
test/models/event_name_test.rb
test/models/payload_request_test.rb
test/models/request_type_test.rb
test/models/resolution_test.rb
test/models/url_test.rb
test/models/user_agent_test.rb
test/test_helper.rb

--created client migration
--created client model 
--set up client relationships 
--set up client test 
--closes 30, 31, 32
--finished iteration 3

Iteration 3

---

app/controllers/server.rb
app/models/client.rb
app/models/referrer.rb
app/models/url.rb
config/environment.rb
test/controllers/server_test.rb
test/test_helper.rb

--finished iteration 4 
--closes #34

Create controller path post sources 33

---

app/controllers/server.rb
test/controllers/server_test.rb

--modified Server controller to have '/sources/:identifier/data'
closes #36

Implemented a post route for payloads

---

app/models/client.rb
test/controllers/server_test.rb
test/models/client_test.rb
test/models/data_loader_test.rb
test/models/event_name_test.rb
test/models/payload_request_test.rb
test/models/request_type_test.rb
test/models/resolution_test.rb
test/models/user_agent_test.rb
test/test_helper.rb

--refactored test helper
--updated/fixed tests

updated tests for new branches

---

app/controllers/server.rb
app/models/client.rb
app/models/requested_at.rb
app/views/event_name.haml
test/models/client_test.rb
test/models/requested_at_test.rb

--new controller method for 24 hour event breakdown
--methods in client - find payloads by event name, parse time
-- created event name view

iteration 8

---

app/views/url.haml

Added return links for a given client when visiting the respective url pages.
Closes #54

Added return links on URL pages back to the client

---

app/controllers/server.rb
test/features/invalid_requests_return_errors_test.rb
test/features/user_can_navigate_to_client_from_event_test.rb
test/features/user_can_navigate_to_client_from_url_test.rb
test/features/user_can_navigate_to_root_test.rb
test/features/user_can_navigate_to_url_from_client_test.rb
test/features/user_can_view_client_test.rb
test/features/user_can_view_event_page_test.rb
test/features/user_can_view_urls_test.rb
test/models/client_test.rb
test/models/payload_request_test.rb
test/test_helper.rb

added feature tests for all views and links

completed feature testing for app closes #56

---

app/controllers/server.rb
app/models/client.rb
app/models/url.rb
app/models/user_agent.rb
test/models/client_test.rb
test/models/url_test.rb

refactor, closes #58
